[build.environment]
  NODE_VERSION = "22"

[build]
  base = "website"
  publish = "dist"

[context.production]
  command = "VITE_HOSTNAME=$URL pnpm test"

[context.deploy-preview]
  command = "VITE_HOSTNAME=$DEPLOY_PRIME_URL pnpm test"

[[redirects]]
  from = "/*"
  to = "https://yomihon.github.io/:splat"
  status = 301
  force = true
